### ISSUE TITLE
mimic's staying connected

### ISSUE THREAD

**Issue by derekbarnett** [frymaster/mumbleclient#1]
If someone joins a channel with the bot, spawns a mimic and then immediately leaves, then the mimic stays connected. This happens whether the mimic has any audio to pass or not. 

They seem to stick around indefinitely. I've got one that's been connected for about 10 hours at this point after someone logged in and then right back off. 

I've been able to reproduce it on my own, although it seems to be somewhat sporadic. I can do it pretty much all of the time with a mimic spawned from a mumble-ruby music bot. However, my normal client connection doesn't appear to be tripping nearly as often. I can reproduce it that way, but not consistently.

**Comment by frymaster** [comment]
There was a race condition when we asked the mimic to disconnect before it had finished connecting.  It didn't yet have a session ID so we couldn't remove it from an internal list which tracks what sessionid mimics have
